DROP TABLE IF EXISTS man;
DROP TABLE IF EXISTS woman;
DROP TABLE IF EXISTS child;
DROP TABLE IF EXISTS man_friend;
DROP TABLE IF EXISTS SEQ_MAN;
DROP TABLE IF EXISTS SEQ_WOMAN;
DROP TABLE IF EXISTS SEQ_CHILD;

CREATE TABLE  `man` (
    `id` INT NOT NULL ,
    `name` VARCHAR( 40 ) NOT NULL,
    `woman_id` INT NULL,
    `created_on` TIMESTAMP NULL,
    `updated_on` TIMESTAMP NULL
);
