app.email.domains:
  '163.com': 'http://mail.163.com/'
  '126.com': 'http://www.126.com/'
  'gmail.com': 'http://mail.google.com/'
  'sina.com.cn': 'http://mail.sina.com.cn/'
  'sina.cn': 'http://mail.sina.com.cn/'
  'vip.sina.cn': 'http://mail.sina.com.cn/'
  '2008.sina.com': 'http://mail.2008.sina.com.cn/'
  'sohu.com': 'http://mail.sohu.com/'
  'tom.com': 'http://mail.tom.com/'
  '139.com': 'http://mail.139.com/'
  'qq.com': 'http://mail.qq.com/'
  'vip.qq.com': 'http://mail.qq.com/'
  'vip.qq.com': 'http://mail.qq.com/'
  'foxmail.com': 'http://foxmail.com/'
  'hotmail.com': 'http://www.hotmail.com/'
  'live.com': 'http://mail.live.com/'
  'yahoo.com.cn': 'http://mail.cn.yahoo.com/'
  'yahoo.cn': 'http://mail.cn.yahoo.com/'
  'yahoo.com': 'http://mail.yahoo.com/'
  'eyou.com': 'http://www.eyou.com/'
  '21cn.com': 'http://mail.21cn.com/'
  'yeah.net': 'http://www.yeah.net/'
  '188.com': 'http://www.188.com/'
  'sogou.com': 'http://mail.sogou.com/'
  '189.cn': 'http://webmail3.189.cn/webmail/'
