---
app.domain.base: 'http://www.taihuoniao.me'
app.domain.static: 'http://static.taihuoniao.me'
app.domain.app: '{$app.domain.base}'

app.url.domain:         '{$app.domain.base}'
app.url.action_base:    '{$app.domain.app}/app/site'
app.url.admin_base:    '{$app.domain.app}/app/admin'
app.url.app_admin_base:    '{$app.domain.app}/app/app_admin'

app.domain.mobile: 'http://wap.taihuoniao.me'
app.url.mobile: '{$app.domain.mobile}'
app.url.wap: '{$app.domain.mobile}'

#wap
app.url.wap.social: '{$app.url.wap}/topic'
app.url.wap.social.list : '{$app.url.wap.social}/list'
app.url.wap.social.show: '{$app.url.wap.social}/view-%s-%s.html'
app.url.wap.shop: '{$app.url.wap}/shop'
app.url.wap.shop.view: '{$app.url.wap}/shop/%s.html'
app.url.wap.active: '{$app.url.wap}/active/list'
app.url.wap.active.view: '{$app.url.wap}/active/view-%s.html'
app.url.wap.try: '{$app.url.wap}/try/list'
app.url.wap.try.view: '{$app.url.wap}/try/view-%s.html'
app.url.wap.my: '{$app.url.wap}/my'
app.url.wap.auth: '{$app.url.wap}/auth'
app.url.wap.stuff: '{$app.url.wap}/stuff'
app.url.wap.stuff.list: '{$app.url.wap.stuff}/c%d/p%s'
app.url.wap.stuff.view: '{$app.url.wap.stuff}/view-%d.html'
app.url.wap.contest: '{$app.url.wap}/contest'
app.url.wap.birdegg: '{$app.url.wap}/birdegg'
app.url.wap.promo: '{$app.url.wap}/promo'

app.url.static: '{$app.domain.static}'
app.url.packaged: '{$app.domain.static}/packaged'
app.url.uncompressed: '{$app.domain.static}/uncompressed'

app.url.js:     '{$app.url.packaged}/js'
app.url.css:    '{$app.url.packaged}/css'
app.url.images: '{$app.url.packaged}/images'

app.url.bundle: '{$app.domain.base}/bundle'


# 首页
app.url.welcome: '{$app.url.action_base}/index/welcome'
app.url.index:	'{$app.url.domain}'

# tag,分类,搜索
app.url.tags: '/tags'
app.url.tag: '/tag'


# 商店
app.url.shop: '{$app.url.domain}/shop'
app.url.shop.list: '{$app.url.shop}'
app.url.shop.view: '{$app.url.shop}/view-%s-%s.html'
app.url.albums: '{$app.url.domain}/albums'
app.url.album.shop: '{$app.url.domain}/albumshop'

# 预售
app.url.sale: '{$app.url.domain}/sale'
app.url.sale.list: '{$app.url.sale}'
app.url.sale.view: '{$app.url.sale}/%s.html'

# 社区
app.url.social: '{$app.url.domain}/social'
app.url.topic: '{$app.url.domain}/topic'
app.url.topic.list : '{$app.url.topic}/list-c%s-t%s-d%s-t%s-p%s.html'
app.url.topic.view: '{$app.url.topic}/view-%s-%s.html'
app.url.vote: '{$app.url.domain}/vote'
app.url.product.subject: '{$app.url.topic}/subject?id=%s&page=%s'

#十万火计
app.url.contest: '{$app.url.domain}/contest'

# 产品灵感
app.url.stuff: '{$app.url.domain}/stuff'
app.url.stuff.list: '{$app.url.stuff}/c%d/p%s'
app.url.stuff.view: '{$app.url.stuff}/view-%d.html'
app.url.stuff.comment: '{$app.url.stuff}/view-%d-%d.html'

# 实验室
app.url.d3in: '{$app.url.domain}/d3in'

# 活动
app.url.active: '{$app.url.domain}/active'
app.url.active.view: '{$app.url.active}/view-%s.html'

# 专题页面
app.url.promo: '{$app.url.domain}/promo'

# 产品编辑
app.url.product: '{$app.url.action_base}/product'

# 社区创意投票
app.url.fever: '{$app.url.domain}/fever'
app.url.fever.list: '{$app.url.fever}/list-c%s-t%s-s%s-p%s.html'
app.url.fever.view: '{$app.url.fever}/%s.html'

# 购物及支付
app.url.shopping: '{$app.url.domain}/shopping'
app.url.cart: '{$app.url.shopping}/cart'
app.url.cart.buy: '{$app.url.shopping}/buy'
app.url.cart.nowbuy: '{$app.url.shopping}/now_buy'

# 地址薄
app.url.address: '{$app.url.action_base}/address'

# 收藏
app.url.favorite: '{$app.url.action_base}/favorite'

# 附件管理
app.url.asset: '{$app.url.action_base}/asset'

# 推荐广告
app.url.advertise.view: '{$app.url.action_base}/tracker?kid=%s'

# 蛋年活动
app.url.birdegg: '{$app.url.domain}/birdegg'

# 合作资源
app.url.cooperate: '{$app.url.action_base}/cooperate'
app.url.cooperate.view: '{$app.url.cooperate}/view?id=%d'

# 大赛地址
app.url.contest: '{$app.url.action_base}/contest'
app.url.contest.show: '{$app.url.contest}/show?id=%d'


# 孵化
app.url.incubator: '{$app.url.domain}/incubator'

# 微信
app.url.wechat: '{$app.url.domain}/wechat'
app.url.mm_shop.view: '{$app.url.wechat}/%s.html'
app.url.jsapi.wxpay: '{$app.url.domain}/wxpay'
app.url.jsapi.wxpay.request: '{$app.url.domain}/wxpay/payment'
app.url.native.wxpay: '{$app.url.domain}/wxpay/direct_native'
app.url.native.feedback: '{$app.url.domain}/wxpay/feedback'
app.url.native.warning: '{$app.url.domain}/wxpay/warning'

# 七牛存储
app.url.qiniu.upload: 'http://up.qiniu.com'
#app.url.qiniu.frbird: 'http://frbird.qiniudn.com'
#app.url.qiniu.frbird: 'http://fs.taihuoniao.com'
app.url.qiniu.frbird: 'https://p4.taihuoniao.com'
#app.url.qiniu.frstatic: 'http://frstatic.qiniudn.com'
app.url.qiniu.frstatic: 'https://s3.taihuoniao.com'
#备用域名
#app.url.qiniu.frbird: 'http://7fvhln.com2.z0.glb.qiniucdn.com'
#app.url.qiniu.frstatic: 'http://7fvhq3.com2.z0.glb.qiniucdn.com'
app.url.qiniu.assets: '{$app.url.action_base}/asset'
app.url.qiniu.onelink: '{$app.url.action_base}/asset/qiniu_onelink'

# 本地存储
app.url.upload: '{$app.url.qiniu.upload}'
app.url.upload.product: '{$app.url.upload}/product'
app.url.upload.topic: '{$app.url.upload}/topic'
app.url.upload.pictures: '{$app.url.upload}/pictures'
app.url.upload.active: '{$app.url.upload}/active'
app.url.upload.stuff: '{$app.url.upload}/stuff'
app.url.upload.cooperate: '{$app.url.upload}/cooperate'
app.url.upload.contest: '{$app.url.upload}/contest'
app.url.upload.report: '{$app.url.upload}/report'

#个人中心
app.url.my:				'{$app.url.domain}/my'
app.url.my.message:		'{$app.url.domain}/my/message'
app.url.my.orders: '{$app.url.domain}/my/orders'
app.url.my.order_view: '{$app.url.domain}/my/order_view?rid=%s'
app.url.my.order_mm_view: '{$app.domain.mobile}/my/order_view?rid=%s'

#实验室
app.url.my.d_order_view: '{$app.url.domain}/my/d_order_view?rid=%s'
app.url.my.d_order_wap_view: '{$app.domain.mobile}/my/d_order_view?rid=%s'

#个人主页
app.url.user:			'{$app.url.domain}/user'
app.url.user.love:		'{$app.url.domain}/user/%s/love'
app.url.user.album:		'{$app.url.domain}/user/%s/album'
app.url.user.view:		'{$app.url.user}/%s'

#在线支付
app.url.alipay: '{$app.url.action_base}/alipay'
app.url.tenpay: '{$app.url.action_base}/tenpay'
app.url.quickpay: '{$app.url.action_base}/quickpay'
app.url.jdpay: '{$app.url.action_base}/jdpay'

#评论
app.url.comment:		'{$app.url.action_base}/comment'

# 产品公测
app.url.try: '{$app.url.domain}/try'
app.url.try.view: '{$app.url.domain}/try/view-%s.html'
app.url.try.comment: '{$app.url.domain}/try/view-%s-%s.html'

#登录,登出,注册,忘记密码,输入邀请码
app.url.auth:		'{$app.url.domain}/auth'
app.url.login: 		'{$app.url.auth}/'
app.url.logout: 	'{$app.url.auth}/logout'
app.url.register: 	'{$app.url.auth}/signup'
app.url.forget: 	'{$app.url.auth}/forget'
app.url.invite: 	'{$app.url.auth}/invite'

app.url.qq.login: '{$app.url.action_base}/qq'
app.url.qq.login_wap: '{$app.url.wap}/app/site/qq?from_to=wap'
app.url.weixin.login: '{$app.url.action_base}/weixin'

#管理面板
app.url.admin:		'{$app.url.admin_base}'
app.url.app_admin:		'{$app.url.app_admin_base}'
app.url.admin.report: '{$app.url.admin_base}/report'
app.url.admin.reply: '{$app.url.admin_base}/reply'

# 附件图片查看地址
app.url.thumb: 		'/uploads/%s'
app.url.asset_view: '/app/site/asset/view?id=%s'

# 搜索
app.url.search: 	'{$app.url.domain}/search'
app.url.search_tag: '{$app.url.domain}/search/search_tag?q='

# 默认的缩略图url
app.url.default_thumb_small: '{$app.url.images}/pic_50x50.gif'
app.url.default_thumb_middle: '{$app.url.images}/pic_180x180.gif'
app.url.default_thumb_big: '{$app.url.images}/pic_580x580.gif'
app.url.default_thumb_middle_height: 180

# 帮助中心
app.url.helper: '{$app.url.action_base}/helper'

app.url.guide: '{$app.url.action_base}/guide'
app.url.about: '{$app.url.guide}/about'
app.url.contact: '{$app.url.guide}/contact'
app.url.join: '{$app.url.guide}/join'

# 图片分享
app.url.share: '{$app.url.domain}/share'

# guide
app.url.guide: '{$app.url.action_base}/guide'

# 单品页面
app.url.goccia: '{$app.url.domain}/goccia'
app.url.goccia.rule: '{$app.url.domain}/activity/goccia'
